#comment this is a comment
GDTOOL=kiki
kuku:all
	@echo stam kuku
all: file2.txt
	@echo all
file1.txt:file0.txt
	@echo file1
	touch file1.txt
file2.txt:file1.txt
	@echo file2
	touch file2.txt
start:
	@echo starting
	touch file0.txt
clean:
	@echo cleaning
	rm *.txt
stam:
	@echo $(GDTOOL)
	echo $(GDTOOL)
