#ifndef __CHAT_H__
#define __CHAT_H__

#include <stddef.h>

typedef enum ReqStats {
REG_SUCCESS, REG_ERR, 
LOGIN_SUCCESS, LOGIN_ERR,
JOIN_GROUP_SUCCESS, JOIN_GROUP_ERR_NOT_FOUND, JOIN_GROUP_ERR_ALREADY_IN,
LEAVE_GROUP_SUCCESS, LEAVE_GROUP_ERR,
LOG_OUT_SUCCESS, LOG_OUT_ERR,
CREATE_GROUP_SUCCESS, CREATE_GROUP_ERR, 
NOT_FOUND, FOUND, FAIL, SUCCESS
} ReqStats;

typedef enum UserChoise
{
    REGISTER = 1,
    LOGIN,
    EXIT,
    CREATE_GROUP,
    JOIN_GROUP,
    SHOWGROUPS,
    LEAVE_GROUP,
    LOG_OUT
} UserChoise;
#endif /*__CHAT_H__*/
